[project]
name = "anonymize-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.8",
    "langchain-ollama>=0.2.0",
    "streamlit>=1.40.2",
    "streamlit-annotation-tools>=1.0.1",
]
